### ISSUE TITLE
vite-ssg incompatible with @ionic/vue

### ISSUE THREAD

**Issue by riderx** [antfu/vite-ssg#125]
```
import { h, Host, proxyCustomElement } from '@stencil/core/internal/client';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/node_modules/.pnpm/@ionic+vue@6.0.0-rc.2/node_modules/@ionic/vue/dist/index.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by NunoSav** [comment]
Have you made any progress on this?

**Comment by riderx** [comment]
i still have random error

**Comment by riderx** [comment]
@NunoSav i found somthing about this :
https://github.com/iamstevendao/vue-tel-input/issues/310
and ionic team gave me a good track to follow :
https://github.com/ionic-team/ionic-framework/issues/24800
```
Ionic imports data from vue-router, which ends up calling defineComponent from Vue. This defineComponent function uses an imported isFunction call. Because there are 2 different instances of Vue bundled, isFunction ends up being undefined.
```
