### ISSUE TITLE
Compatibility issue with v-calendar

### ISSUE THREAD

**Issue by techieoriname** [antfu/vite-ssg#129]
I am currently trying to implement `v-calendar` package.

plugin fiile

```typescript
import VCalendar from "v-calendar";
import { UserModule } from "~/utils/types";

export const install: UserModule = ({ isClient, router, app }) => {
    if (!isClient) return;
    app.use(VCalendar, {});
};
```

when I run `build`, I get an error(output below).
```
ReferenceError: window is not defined
    at getDefault (.../node_modules/v-calendar/lib/cjs/index-1621a98b.js:3675:5)
    at Object.<anonymous> (.../ssr/node_modules/v-calendar/lib/cjs/index-1621a98b.js:3686:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (.../ssr/node_modules/v-calendar/lib/cjs/index.js:1:141)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

please help with this, I think I need to maybe import dynamically.

**Comment by userquin** [comment]
@techieoriname I assume you're using `vitesse template`...

1) switch `UserModule` to be `async`: `export type UserModule = (ctx: ViteSSGContext) => Promise<void>`
2) change the module with this:
```ts
// import VCalendar from "v-calendar"; <=== COMMENT OUT OR REMOVE THIS IMPORT
import { UserModule } from "~/utils/types";

export const install: UserModule = async({ isClient, router, app }) => {
    if (!isClient) return;
    const calendar = await import('v-calendar')
    app.use(calendar.default || calendar, {});
};
```

If you need to await `VCalendar` to be registered, then change also `main.ts` with this one:
```ts
// https://github.com/antfu/vite-ssg
export const createApp = ViteSSG(
  App,
  { routes },
  async(ctx) => {
    // install all modules under `modules/`
    await Promises.all(Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx)))
  },
)
```
