### ISSUE TITLE
Vitesse build error on windows

### ISSUE THREAD

**Issue by SilenceDN** [antfu/vite-ssg#151]
```
node v14.17.6
vite-ssg 0.17.0
```
Start with
> npx degit antfu/vitesse my-vitesse-app

An error occurred when I tried to build
```bash
pnpm build
```

```
 UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid 
file:// URLs. Received protocol 'd:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:791:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at build (file:///D:/playground/my-vitesse-app/node_modules/.pnpm/vite-ssg@0.17.0_82ac6e1c953435653ed81a7f1ca75ffa/node_modules/vite-ssg/dist/node/cli.mjs:182:40)
    at async Object.handler (file:///D:/playground/my-vitesse-app/node_modules/.pnpm/vite-ssg@0.17.0_82ac6e1c953435653ed81a7f1ca75ffa/node_modules/vite-ssg/dist/node/cli.mjs:295:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:32412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
I tried to fix the problem . It works.

```javascript
//vite-ssg>dist>node>cli.mjs 
181 const prifix =  process.platform === "win32" ? 'file://' : '';
182 const { createApp } = await import(join(prifix, ssgOut, `${parse(ssrEntry).name}.mjs`));
183 const { routes } = await createApp(false);

```

I don’t know what to do, is this a bug?

**Comment by SilenceDN** [comment]
> Glad you figured out the fix. How about sending a PR to vite-ssg? Thanks

Please ignore ae48fd4 😅
