### ISSUE TITLE
window is not defined  - what is correct way to import component inside vite-ssg?

### ISSUE THREAD

**Issue by spokospace** [antfu/vite-ssg#154]
What is correct way to use client side component with vite-ssg?

code: https://stackblitz.com/edit/github-ijnjm5?file=src%2Fpages%2F[lang]%2Fdocs%2F[doc].vue

I used <client-only> but still have issue when building with vite-ssg. What's wrong with it?

```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:7) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at eval (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:2141:3)
    at new Promise (<anonymous>)
    at Array.Object.defineProperty.value (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:2140:24)
    at __w_pdfjs_require__ (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:10060:41)
    at Array.Object.defineProperty.value (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:1040:17)
    at __w_pdfjs_require__ (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:10060:41)
    at Array.pdfjsLib (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:51:25)
    at __w_pdfjs_require__ (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:10060:41)
    at eval (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:10192:33)
    at eval (/home/projects/github-ijnjm5/node_modules/pdfjs-dist/legacy/web/pdf_viewer.js:10220:3)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by KaelWD** [comment]
https://v3.vuejs.org/guide/ssr/universal.html#access-to-platform-specific-apis

**Comment by userquin** [comment]
https://github.com/antfu/vite-ssg/issues/21#issuecomment-862333958
https://github.com/antfu/vite-ssg/issues/90
