### ISSUE TITLE
firebase/app is not supported resolving ES modules imported fro

### ISSUE THREAD

**Issue by u007** [antfu/vite-ssg#167]
```
cross-env NODE_ENV=production vite-ssg build
```
throws this error:

```
UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'project/node_modules/firebase/app' is not supported resolving ES modules imported from project/.vite-ssg-temp/main.mjs
Did you mean to import firebase@8.10.0/node_modules/firebase/app/dist/index.cjs.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:304:17)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)
```

**Comment by u007** [comment]
using "firebase": "^8.10.0",

**Comment by userquin** [comment]
@u007 try changing to `cjs` using `format: 'cjs'` on `ssgOptions`.
