### ISSUE TITLE
ResizeObserver causes `ReferenceError`

### ISSUE THREAD

**Issue by DerYeger** [antfu/vite-ssg#179]
I'm using ResizeObserver in a [project of mine](https://github.com/DerYeger/jan-mueller/tree/next).
The pages are generated fine, except that a `ReferenceError` is thrown during the build.

```
ReferenceError: ResizeObserver is not defined
    at setup (/home/runner/work/jan-mueller/jan-mueller/node_modules/@yeger/vue-masonry-wall/dist/masonry-wall.umd.js:1:1249)
    at callWithErrorHandling (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5404:22)
    at setupStatefulComponent (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5120:29)
    at setupComponent (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5101:11)
    at renderComponentVNode (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:195:17)
    at ssrRenderComponent (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:620:12)
    at file:///home/runner/work/jan-mueller/jan-mueller/.vite-ssg-temp/main.mjs:2921:13
    at renderComponentSubTree (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:260:13)
    at renderComponentVNode (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:211:16)
    at renderVNode (/home/runner/work/jan-mueller/jan-mueller/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:301:22)
[Vue warn]: Component  is missing template or render function.
```

See https://github.com/DerYeger/jan-mueller/runs/4907933986?check_suite_focus=true for a build log displaying the issue.

**Comment by sibbng** [comment]
`MasonryWall` component doesn't support SSR. Wrap it with [ClientOnly](https://github.com/antfu/vite-ssg#clientonly) component.

**Comment by sibbng** [comment]
It seems this component comes from your package. You need to create the `ResizeObserver` when the component is mounted or `window` is exist:
```ts
if (typeof window !== 'undefined') {
  //...
}
```

**Comment by DerYeger** [comment]
> It seems this component comes from your package. You need to create the `ResizeObserver` when the component is mounted or `window` is exist:
> 
> ```ts
> if (typeof window !== 'undefined') {
>   //...
> }
> ```

Yes, that would be a solution, but only for a single use case.

I was thinking that maybe it would be possible to provide a mock ResizeObserver during the SSG.
Would it be possible to add something like that?

**Comment by DerYeger** [comment]
I fixed the issue by adding a dummy ResizeObserver for the SSG.

```ts
export const createApp = ViteSSG(
  App,
  { routes, base: import.meta.env.BASE_URL },
  (ctx) => {
    if (import.meta.env.SSR) {
      /* eslint-disable @typescript-eslint/no-empty-function */
      // eslint-disable-next-line no-global-assign
      global.ResizeObserver = class DummyResizeObserver {
        public constructor() {}
        public disconnect() {}
        public observe() {}
        public unobserve() {}
      }
      /* eslint-enable @typescript-eslint/no-empty-function */
    }
  }
)
```

@antfu Are you interested in making this part of `vite-ssg`? I could create a PR.

**Comment by DerYeger** [comment]
In the meantime, I created [vite-plugin-ssg-utils](https://github.com/DerYeger/vite-plugin-ssg-utils), which provides a dummy `ResizeObserver` for SSG (or SSR) builds
