### ISSUE TITLE
[QUESTION] - How can I configure vite-ssg to use client-only package and make it build compatible?

### ISSUE THREAD

**Issue by sujit-baniya** [antfu/vite-ssg#181]
I've been trying to make client-only package by adding tag `<client-only>`. And also by checking on composables. Nothing is working. 

For e.g.
When I tried to build https://github.com/vueup/vue-quill with vite-ssg, I get following error

```js
ReferenceError: document is not defined
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ```

Please suggest if there's any of such configuration or any fixed I could apply

**Comment by sujit-baniya** [comment]
I tried with the suggestion from https://github.com/antfu/vite-ssg/issues/74. I don't see any error but it is not displayinng anything on browser

**Comment by sujit-baniya** [comment]
Got it working using

```js
import('@vueup/vue-quill').then((module) => editor.value = module.QuillEditor)
```

```vue
<component
									:is="editor"
									v-bind="{
										theme: 'snow',
										contentType: 'html',
									}"
									v-model:content="content"
								/>
```
