### ISSUE TITLE
[BUG] - Build error with dayjs

### ISSUE THREAD

**Issue by sujit-baniya** [antfu/vite-ssg#182]
Version: vite-ssg 0.17.6
Getting error when trying to build app with `dayjs`

Error:
```js
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:3355671) UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/web/node_modules/dayjs/plugin/advancedFormat' imported from /web/.vite-ssg-temp/main.mjs
Did you mean to import dayjs@1.10.7/node_modules/dayjs/plugin/advancedFormat.js?
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3355671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:3355671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sujit-baniya** [comment]
@cimchd I removed dayjs and now getting same error on other package. IT seems the problem is specific to v0.17.6

**Comment by cimchd** [comment]
Take a look at the code that caused this error:  `(node:3355671) UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/web/node_modules/dayjs/plugin/advancedFormat' imported from /web/.vite-ssg-temp/main.mjs`.

If the build fails the .vite-ssg-temp/main.mjs file should still be there. Check the import paths there. There is probably the reason why the import fails.

If you can't figure it out yourself, provide a minimal repo that reproduces this error.

**Comment by sujit-baniya** [comment]
@cimchd I did add this
`format: 'cjs'`
 here
```js
  ssgOptions: {
    script: 'async',
    formatting: 'minify',
    format: 'cjs',
  },
```
And it worked
