### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ShawnZhou2000** [antfu/vite-ssg#189]
vite: 2.7.2
vite-ssg: 0.17.9
node: 14.18.1
I'm using vite-ssg to genterate static pages, `npm run dev` is OK, but when I run `npm run build`, it didn't work.
I don't know what's wrong with it, please tell me what should I do, thanks a lot.
Here are some informations:
```
[vite-ssg] Build for client...
vite v2.7.13 building for production...
✓ 34 modules transformed.
dist/index.html                  0.48 KiB
dist/ssr-manifest.json           2.54 KiB
dist/assets/app.435bf692.js      2.06 KiB / gzip: 1.05 KiB
dist/assets/bar.1d77fe31.js      0.48 KiB / gzip: 0.34 KiB
dist/assets/foo.8134e6b6.js      0.23 KiB / gzip: 0.21 KiB
dist/assets/app.66a1d137.css     0.13 KiB / gzip: 0.12 KiB
dist/assets/vendor.e042ed43.js   80.85 KiB / gzip: 31.90 KiB

[vite-ssg] Build for server...
vite v2.7.13 building SSR bundle for production...
✓ 9 modules transformed.
.vite-ssg-temp/main.mjs                    4.27 KiB
.vite-ssg-temp/assets/style.bb3d87dd.css   0.15 KiB

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:15724) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at useHistoryStateNavigation (E:\html\vite-ssg-demo\node_modules\vue-router\dist\vue-router.cjs.js:505:35)
    at createWebHistory (E:\html\vite-ssg-demo\node_modules\vue-router\dist\vue-router.cjs.js:597:31)
    at file:///E:/html/vite-ssg-demo/.vite-ssg-temp/main.mjs:46:12
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async build (E:\html\vite-ssg-demo\node_modules\vite-ssg\dist\node\cli.cjs:180:44)
    at async Object.handler (E:\html\vite-ssg-demo\node_modules\vite-ssg\dist\node\cli.cjs:313:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:15724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

vite.config.ts:
```
import VitePages from "vite-plugin-pages";
import { resolve } from "path";
import fs from "fs-extra";
import matter from "gray-matter";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import ViteMarkdown from "vite-plugin-md";
import ViteComponents from "vite-plugin-components";

// plugins settings
export default defineConfig({
  plugins: [
    vue({
      include: [/\.vue$/, /\.md$/],
    }),
    VitePages({
      extensions: ["vue", "md"],
      pagesDir: "src/pages",
      extendRoute(route) {
        const path = resolve(__dirname, route.component.slice(1));
        const md = fs.readFileSync(path, "utf-8");
        const { data } = matter(md);
        route.meta = Object.assign(route.meta || {}, { frontmatter: data });
        return route;
      },
    }),
    ViteMarkdown(),
    ViteComponents({
      extensions: ["vue", "md"],
      customLoaderMatcher: (path) => path.endsWith(".md"),
    }),
  ]
});
```

**Comment by userquin** [comment]
check this issues:
- https://github.com/antfu/vite-ssg/issues/21#issuecomment-862333958
- https://github.com/antfu/vite-ssg/issues/90
