### ISSUE TITLE
"ReferenceError: window is not defined" when router options contains "history"  during "npm run build"

### ISSUE THREAD

**Issue by frck006** [antfu/vite-ssg#20]
### **Error:**

```
[vite-ssg] Build for server...
building SSR bundle for production...
✓ 50 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.38kb
.vite-ssg-temp/registerSW.js               0.13kb
.vite-ssg-temp/main.js                     74.48kb
.vite-ssg-temp/assets/style.824805e5.css   29.26kb
ReferenceError: window is not defined
    at useHistoryStateNavigation (C:\_Franck\vite01\node_modules\.pnpm\vue-router@4.0.3_vue@3.0.5\node_modules\vue-router\dist\vue-router.cjs.js:502:35)
    at Object.createWebHistory (C:\_Franck\vite01\node_modules\.pnpm\vue-router@4.0.3_vue@3.0.5\node_modules\vue-router\dist\vue-router.cjs.js:594:31)
    at Module.<anonymous> (C:\_Franck\vite01\.vite-ssg-temp\main.js:2801:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at build (C:\_Franck\vite01\node_modules\.pnpm\vite-ssg@0.8.9_09776a6a773b9a81449cdda32cab3c64\node_modules\vite-ssg\dist\node\cli.js:134:23)
 ERROR  Command failed with exit code 1.
```

### **main.ts:**

```
export const createApp = ViteSSG(
  App,
  { 
    routes, 
    history: createWebHistory('dist')
  },
  (ctx) => {
    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))
  },
)
```

**Comment by antfu** [comment]
The `history` field is automatic by SSG, and we omit the type from it where you should already see the TypeScript warnings. But I also understand what you are trying to achieve, so since 0.8.10, now you can have this instead:

```ts
export const createApp = ViteSSG(
  App,
  { 
    routes, 
    base: 'dist',
  },
  (ctx) => {
    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))
  },
)
```

**Comment by frck006** [comment]
Thank you. The build works.

Yes, I try to put the result of the build in Tomcat application.
I changed the "base" and the URL 'http://localhost:8080/dist' is ok but 'js' are always in "http://localhost:8080/assets". 
It should be 'http://localhost:8080/dist/assets', no ?

![image](https://user-images.githubusercontent.com/10244725/108676574-ba31e980-74e8-11eb-9e90-7e992205107b.png)

**Comment by antfu** [comment]
This base is for vue-router only. Where you will also need to configure the base for Vite to achieve what you want.

**Comment by frck006** [comment]
In "vite.config.ts" ?

**Comment by antfu** [comment]
https://vitejs.dev/config/#base

Please read the docs

**Comment by frck006** [comment]
Oups, you're right.

Can I suggest that the default value for vue-router's base could be the same from vite.config's base ?

**Comment by rainmanhhh** [comment]
so it's impossible to use createWebHashHistory?
