### ISSUE TITLE
vite-ssg build incompatiable with rpc-websockets

### ISSUE THREAD

**Issue by tshemeng** [antfu/vite-ssg#22]
demo: https://github.com/tshemeng/test_vitesse

`vite build` works but `vite-ssg build` failed.

`vite-ssg build` output
```
[vite-ssg] Build for server...
building SSR bundle for production...
✓ 45 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.38kb
.vite-ssg-temp/registerSW.js               0.13kb
.vite-ssg-temp/main.js                     64.29kb
.vite-ssg-temp/assets/style.f249232f.css   21.64kb
E:\test_vitesse\node_modules\.pnpm\rpc-websockets@7.4.8\node_modules\rpc-websockets\build-ts\index.browser.js:2
import WebSocketBrowserImpl from "./lib/client/websocket.browser";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (E:\test_vitesse\.vite-ssg-temp\main.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
 ERROR  Command failed with exit code 1.
```

**Comment by antfu** [comment]
It's a problem with `rpc-websockets`, their pacakage.json entries are incorrect. https://github.com/elpheria/rpc-websockets/blob/master/package.json
