### ISSUE TITLE
TypeError: route.endsWith is not a function

### ISSUE THREAD

**Issue by wind-rain666** [antfu/vite-ssg#223]
I want to use dynamic route with vite-ssg, but I can't find the problem
```
// main.ts
  export async function includedRoutes(paths:string[], routes:RouteRecordRaw[]) {
    // Sensitive key is managed by Vite - this would not be available inside
    // vite.config.js as it runs before the environment has been populated.
    return Promise.all(
      routes.flatMap(async(route) => {
        return route.name === 'product'
          ? (await axios.get('http://localhost:1337/api/products')).data.data.map((item:any) => `/product/${item.id}`)
          : route.path
      }),
    )
    
  }
```
```
/router/index.ts
export const routes = [
    {
        path: '/',
        name: 'index',
        redirect: '/test'
    },
    {
        path: '/test',
        name: 'test',
        component: Test
    },
    {
        path: '/product/:id',
        name: 'product',
        component: () => import('../views/product.vue')
    }
]
```

```
(node:8608) UnhandledPromiseRejectionWarning: Error: [vite-ssg] Error on page: /product/1
TypeError: route.endsWith is not a function
    at E:\code\vite-ssg\vite-ssg-demo\node_modules\.pnpm\registry.npmmirror.com+vite-ssg@0.19.0_ae019cd7b4f401fe90b85d88eaf2d274\node_modules\vite-ssg\dist\chunks\build.cjs:221:43
    at async Promise.all (index 2)
    at async Object.build (E:\code\vite-ssg\vite-ssg-demo\node_modules\.pnpm\registry.npmmirror.com+vite-ssg@0.19.0_ae019cd7b4f401fe90b85d88eaf2d274\node_modules\vite-ssg\dist\chunks\build.cjs:195:3)
    at async Object.handler (E:\code\vite-ssg\vite-ssg-demo\node_modules\.pnpm\registry.npmmirror.com+vite-ssg@0.19.0_ae019cd7b4f401fe90b85d88eaf2d274\node_modules\vite-ssg\dist\node\cli.cjs:25:3) 
    at E:\code\vite-ssg\vite-ssg-demo\node_modules\.pnpm\registry.npmmirror.com+vite-ssg@0.19.0_ae019cd7b4f401fe90b85d88eaf2d274\node_modules\vite-ssg\dist\chunks\build.cjs:227:13
    at async Promise.all (index 2)
    at async Object.build (E:\code\vite-ssg\vite-ssg-demo\node_modules\.pnpm\registry.npmmirror.com+vite-ssg@0.19.0_ae019cd7b4f401fe90b85d88eaf2d274\node_modules\vite-ssg\dist\chunks\build.cjs:195:3)
    at async Object.handler (E:\code\vite-ssg\vite-ssg-demo\node_modules\.pnpm\registry.npmmirror.com+vite-ssg@0.19.0_ae019cd7b4f401fe90b85d88eaf2d274\node_modules\vite-ssg\dist\node\cli.cjs:25:3) 
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:8608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
dist/index.html       1.35 KiB
dist/test.html        1.35 KiB
```

**Comment by hasan-almujtaba** [comment]
I also get this problem, fyi you can do this easily in nuxt (https://nuxtjs.org/docs/configuration-glossary/configuration-generate#routes).

**Comment by hasan-almujtaba** [comment]
looks like i found a solution, this code works for me.

```
ssgOptions: {
    script: 'async',
    formatting: 'minify',
    async includedRoutes(paths) {
      const { data: post } = await api.get('posts')
      const staticPaths = paths.filter(path => !path.includes(':'))

      const dynamicPosts = post.map((item: any) => `/example/${item.id}`)

      return [...staticPaths, ...dynamicPosts]
    },
  },
```

**Comment by timstallmann** [comment]
I'm having this issue too and not clear what a solution might be in my case.. anyone else have ideas?
