### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by falstack** [antfu/vite-ssg#23]
### repo
[https://github.com/calibur-tv/arthur](https://github.com/calibur-tv/arthur)

### step
```sh
clone repo
yarn install
yarn workspace core build
```

### error message

```sh
yarn workspace core build

[vite-ssg] Build for client...
vite v2.0.2 building for production...
✓ 18 modules transformed.
dist/index.html                  0.47kb
dist/ssr-manifest.json           1.45kb
dist/assets/index.84deefdb.js    0.14kb / brotli: 0.11kb
dist/assets/about.b281ebe7.js    0.14kb / brotli: 0.10kb
dist/assets/app.63e62a7a.css     0.16kb / brotli: 0.10kb
dist/assets/app.6e05f1be.js      2.13kb / brotli: 1.01kb
dist/assets/vendor.a9bc8345.js   68.26kb / brotli: 23.85kb

[vite-ssg] Build for server...
vite v2.0.2 building SSR bundle for production...
✓ 6 modules transformed.
.vite-ssg-temp/main.js                     4.08kb
.vite-ssg-temp/assets/style.20813ca4.css   0.20kb
ReferenceError: window is not defined
    at useHistoryStateNavigation (/Users/yuistack/Documents/calibur/arthur/node_modules/vue-router/dist/vue-router.cjs.js:501:35)
    at Object.createWebHistory (/Users/yuistack/Documents/calibur/arthur/node_modules/vue-router/dist/vue-router.cjs.js:593:31)
    at Module.<anonymous> (/Users/yuistack/Documents/calibur/arthur/packages/core/.vite-ssg-temp/main.js:65:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at build (/Users/yuistack/Documents/calibur/arthur/node_modules/vite-ssg/dist/node/cli.js:134:23)
```

### system info
- node：v14.15.1

**Comment by antfu** [comment]
https://www.github.com/calibur-tv/arthur/tree/main/packages%2Fcore%2Fsrc%2Froute%2Findex.js

**Comment by falstack** [comment]
@antfu ？ what's meaning?

**Comment by rafalolszewski94** [comment]
> [github.com/calibur-tv/arthur/tree/main/packages%2Fcore%2Fsrc%2Froute%2Findex.js](https://www.github.com/calibur-tv/arthur/tree/main/packages%2Fcore%2Fsrc%2Froute%2Findex.js)

this link returns 404, please update answer (or readme preferably)

**Comment by anhzf** [comment]
> > [github.com/calibur-tv/arthur/tree/main/packages%2Fcore%2Fsrc%2Froute%2Findex.js](https://www.github.com/calibur-tv/arthur/tree/main/packages%2Fcore%2Fsrc%2Froute%2Findex.js)
> 
> this link returns 404, please update answer (or readme preferably)
> 
> edit:
> nevermind, found it out it's a repo link mentioned in OP post; nonetheless - still getting `window is not defined` error and it's not in Vue Router package.

it is solved? I've get this error too

**Comment by userquin** [comment]
@anhzf see https://github.com/antfu/vite-ssg/issues/21#issuecomment-862333958

**Comment by anhzf** [comment]
> @anhzf see [#21 (comment)](https://github.com/antfu/vite-ssg/issues/21#issuecomment-862333958)

thanks, but the problem is solved. it is because I'm trying to using web history on routeOptions even though the default of vite-ssg is using web history
