### ISSUE TITLE
primevuew build is failed

### ISSUE THREAD

**Issue by rkrajukhunt** [antfu/vite-ssg#240]
PWA v0.11.13
mode      generateSW
precache  34 entries (757.90 KiB)
files generated
  dist\sw.js
  dist\workbox-3c99db12.js

[vite-ssg] Build for server...
vite v2.8.6 building SSR bundle for production...
transforming...
Γ£ô 137 modules transformed.
rendering chunks...
.vite-ssg-temp/manifest.webmanifest        0.38 KiB
.vite-ssg-temp/main.mjs                    405.00 KiB
.vite-ssg-temp/assets/style.d14d9429.css   198.74 KiB

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:1632) UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Users\RajuKhunt\Accelsiors-Workspace\emperorbrains\esteemed\esteemed-colleagues\client\node_modules\primevue\config' is not supported resolving ES modules imported from C:\Users\RajuKhunt\Accelsiors-Workspace\emperorbrains\esteemed\esteemed-colleagues\client\.vite-ssg-temp\main.mjs
Did you mean to import primevue@3.12.6_vue@3.2.31/node_modules/primevue/config/config.cjs.js?
    at finalizeResolution (internal/modules/esm/resolve.js:272:17)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:1632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by userquin** [comment]
try using `format: 'cjs'` on `ssgOptions`

**Comment by wohui** [comment]
i got a similar error while run "npm run build",then run "node .output/server/index.mjs"
got the error info:
 .output/server/node_modules/primevue/api' is not supported resolving ES modules imported from ...../server.mjs
Did you mean to import primevue/api/api.cjs.js?
  at new NodeError (node:internal/errors:377:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:401:17)  
  at moduleResolve (node:internal/modules/esm/resolve:966:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1174:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)  
  at link (node:internal/modules/esm/module_job:78:36)
[nitro] Error while generating error response FetchError: 404 Not Found

**Comment by xeno** [comment]
Update your nuxt.config.ts to transpile the primevue library and it will work.

```import { defineNuxtConfig } from 'nuxt';

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: ['primevue']
  }
});```

**Comment by lukkyjoe** [comment]
thank you @xeno . Your suggestion worked for me. Would you mind explaining why that's necessary?
