### ISSUE TITLE
Entry auto detection

### ISSUE THREAD

**Issue by feryardiant** [antfu/vite-ssg#27]
Hi, I just try the plugin and got these error

```
[vite-ssg] Build for server...
vite v2.0.5 building SSR bundle for production...
✓ 0 modules transformed.
Could not resolve entry module (src\main.ts).
Error: Could not resolve entry module (src\main.ts).
    at error (my-app\node_modules\.pnpm\rollup@2.41.0\node_modules\rollup\dist\shared\rollup.js:5285:30)
    at ModuleLoader.loadEntryModule (my-app\node_modules\.pnpm\rollup@2.41.0\node_modules\rollup\dist\shared\rollup.js:18440:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
 ERROR  Command failed with exit code 1.
```

then I check the source, I found this

https://github.com/antfu/vite-ssg/blob/9fbb88b2f620b928e5d53b3a80447c639b7d2978/src/node/build.ts#L31-L40

So, I try to add `--entry=src/main.js` to my `package.json` scripts

```json
{
  "scripts": {
    "dev": "vite",
    "build": "vite build",
-    "generate": "cross-env NODE_ENV=production vite-ssg build",
+    "generate": "cross-env NODE_ENV=production vite-ssg build --entry=src/main.js",
    "prepare": "husky install"
  }
}
```

Would be nice to see it automatically detect the build `entry` instead of we have to manually add it as argument.

**Comment by hannoeru** [comment]
In other ways, you can set it inside vite config like:

```js
// vite.config.js
module.export = {
  ssgOptions: {
    entry: 'src/main.js'
  }
}
```
