### ISSUE TITLE
Building vue3 project with vuelidate import error

### ISSUE THREAD

**Issue by rezelute** [antfu/vite-ssg#280]
### Describe the bug

Hi,
I am sorry if this is not a bug in vite-ssg but im finding it very hard to know whats causing this issue. If you could point me in the right direction I would appreciate it 😃 .

I am using the following packages:
`"vite-ssg": "^0.20.2",`
`"@vuelidate/core": "^2.0.0-alpha.43",`
`"@vuelidate/validators": "^2.0.0-alpha.31",`

In a test.vue file I then `import useVuelidate from "@vuelidate/core";`. 

Package.json contains: `"type": "module",`

When i try to build the project using: `vue-tsc --noEmit && vite-ssg build`
I get the following error:

```
.vite-ssg-temp/assets/style.9e50c03e.css             70.19 KiB
(node:47652) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:47652) UnhandledPromiseRejectionWarning: C:\...\node_modules\@vuelidate\core\dist\index.esm.js:1
import { isReactive, isReadonly, computed, unref, ref, watch, reactive, isRef, nextTick, inject, provide, getCurrentInstance, onBeforeMount, onBeforeUnmount } from 'vue-demi';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async build (file:///C:/.../node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///C:/.../node_modules/vite-ssg/dist/node/cli.mjs:20:3)
(node:47652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:47652) UnhandledPromiseRejectionWarning: C:\...\node_modules\@vuelidate\core\dist\index.esm.js:1
import { isReactive, isReadonly, computed, unref, ref, watch, reactive, isRef, nextTick, inject, provide, getCurrentInstance, onBeforeMount, onBeforeUnmount } from 'vue-demi';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async build (file:///C:/.../node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///C:/.../node_modules/vite-ssg/dist/node/cli.mjs:20:3)
(node:47652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```

### Reproduction

Try using vuelidate with vite-ssg

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 15.68 GB / 31.92 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rezelute** [comment]
Note that after adding `format: "cjs",` I am running into another error but on CI:
```
failed to load config from /root/project/.../vite.config.ts
error when starting dev server:
/root/project/.../node_modules/vite-plugin-windicss/dist/index.js:239
            ].join("\n").replace("__POST_PATH__", (((_a = config.server) == null ? void 0 : _a.origin) ?? "") + POST_PATH);
                                                                                                        ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/project/participant/vite.config.ts:31:43)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (/root/project/participant/node_modules/vite/dist/node/chunks/dep-689425f3.js:62006:20)
npm ERR! code ELIFECYCLE
```

**Comment by emhamzahazeen** [comment]
Ran into the similar issue while using npm, even without modification to any file directly after clone and "npm i" the build fails. Need to investigate the compatibility issue. Pointers are welcomed!

**Comment by Codermar** [comment]
I have a similar issue which might be related. I am unable to build the app.

I have a fairly standard vitesse setup with dependencies up to date. In my case I am using an internal web component library which I tried both via CDN and pnpm install. I know it is SSG related because the same library builds fine on an out of the box `npm init vue@latest` setup

Here's my log:
```
[vite-ssg] Build for client...
vite v3.0.9 building for production...
✓ 440 modules transformed.
(node:14253) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
rendering chunks (62)...[vite:esbuild-transpile] Transform failed with 1 error:
assets/app.61dd79f9.js:18326:2: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
18324|
18325|  if ({"BASE_URL":"/","MODE":"production","DEV":false,"PROD":true}.VITE_MSW_ENABLED === "true")
18326|    await __vitePreload(() => import('./browser.9a68372b.js'),true?"__VITE_PRELOAD__":void 0);
   |    ^
18327|  const routes = setupLayouts(routes$1);
18328|  ViteSSG(_sfc_main, { routes, base: "/" }, (ctx) => {


PWA v0.12.4
mode      generateSW
precache  6 entries (7.94 KiB)
files generated
  dist/sw.js
  dist/workbox-f51ab5e4.js

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/usr/local/apple/okapi-admin-app-next/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:1605
  let error = new Error(`${text}${summary}`);
              ^

Error: Transform failed with 1 error:
assets/app.61dd79f9.js:18326:2: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    at failureErrorWithLog (/usr/local/apple/okapi-admin-app-next/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:1605:15)
    at /usr/local/apple/okapi-admin-app-next/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:1394:29
    at /usr/local/apple/okapi-admin-app-next/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/usr/local/apple/okapi-admin-app-next/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/usr/local/apple/okapi-admin-app-next/node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 2,
        file: 'assets/app.61dd79f9.js',
        length: 5,
        line: 18326,
        lineText: `  await __vitePreload(() => import('./browser.9a68372b.js'),true?"__VITE_PRELOAD__":void 0);`,
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)'
    }
  ],
  warnings: [],
  frame: '\n' +
    '\x1B[33mTop-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)\x1B[39m\n' +
    '18324|  \n' +
    '18325|  if ({"BASE_URL":"/","MODE":"production","DEV":false,"PROD":true}.VITE_MSW_ENABLED === "true")\n' +
    `18326|    await __vitePreload(() => import('./browser.9a68372b.js'),true?"__VITE_PRELOAD__":void 0);\n` +
    '   |    ^\n' +
    '18327|  const routes = setupLayouts(routes$1);\n' +
    '18328|  ViteSSG(_sfc_main, { routes, base: "/" }, (ctx) => {\n',
  loc: {
    column: 2,
    file: 'assets/app.61dd79f9.js',
    length: 5,
    line: 18326,
    lineText: `  await __vitePreload(() => import('./browser.9a68372b.js'),true?"__VITE_PRELOAD__":void 0);`,
    namespace: '',
    suggestion: ''
  },
  code: 'PLUGIN_ERROR',
  plugin: 'vite:esbuild-transpile',
  hook: 'renderChunk'
}

Node.js v18.7.0
```

**Comment by odex21** [comment]
Same error, I think it cause by vite@3.

**Comment by amir20** [comment]
Confirmed this breaks with latest version of `vite@3.1.0`

**Comment by amir20** [comment]
Interestingly when I add `type: "module"` to package.json it works.

**Comment by dobromir-hristov** [comment]
@amir20 can you tell me where you added `type: "module"` , to which `package.json` ?

**Comment by amir20** [comment]
@dobromir-hristov See my change https://github.com/amir20/amir20.github.io/commit/834b7a86ee2417c53d2b7cb8f2161ba4ff0c2f69#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R5 

I added it to my own package.json file. I also saw the error which suggested the same thing.

**Comment by joeyhuang0235** [comment]
Needs reproduction.
