### ISSUE TITLE
why vue-i18n cannot build with vite-ssg

### ISSUE THREAD

**Issue by saronwei** [antfu/vite-ssg#286]
I'm running the vite-ssg build, but the console always show these informations:

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:17492) UnhandledPromiseRejectionWarning: file:///E:/01_Workstation/03_Codes/Vue3/whatever-fronted/.vite-ssg-temp/main.mjs:3
import { createI18n, useI18n } from 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js';
                     ^^^^^^^
SyntaxError: Named export 'useI18n' not found. The requested module 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js';
const { createI18n, useI18n } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async build (file:///E:/01_Workstation/03_Codes/Vue3/whatever-fronted/node_modules/.pnpm/vite-ssg@0.20.2_gv3f3qqio2remjcjfesyn4w42y/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)    
    at async Object.handler (file:///E:/01_Workstation/03_Codes/Vue3/whatever-fronted/node_modules/.pnpm/vite-ssg@0.20.2_gv3f3qqio2remjcjfesyn4w42y/node_modules/vite-ssg/dist/node/cli.mjs:20:3) 
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't why cause this problem

**Comment by yashika** [comment]
me too

**Comment by websitevirtuoso** [comment]
I have next error
```
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/home/viktord/Projects/renthome/dashboard/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:6
import { getGlobalThis, format, makeSymbol, isPlainObject, isArray, isString, hasOwn, isObject, isBoolean, isRegExp, isFunction, inBrowser, assign, isNumber, warn, createEmitter, isEmptyObject } from '@intlify/shared';
^^^^^^

SyntaxError: Cannot use import statement outside a module

```

**Comment by lichingchester** [comment]
same here

**Comment by bart** [comment]
I mean you can set `"type": "module"` in your package.json file but this might brake something else. Super annoying this back and force with CommonJS and ES

**Comment by yankeeinlondon** [comment]
> I mean you can set `"type": "module"` in your package.json file but this might brake something else. Super annoying this back and force with CommonJS and ES

I ran into this problem and get the error regardless of whether my `type` is set to "module" or "commonjs".

**Comment by ovrays** [comment]
Update your ssr configuration in vite.config.ts:
```ts
export default defineConfig({
  plugins: [vue, vueI18n({
    include: resolve(dirname(fileURLToPath(import.meta.url)), './locales/**'),
  })],
  ssr: {
    // SSG Vue-i18n workaround
    noExternal: ['workbox-window', /vue-i18n/],
  }
})
```

**Comment by saronwei** [comment]
> Update your ssr configuration in vite.config.ts:
> 
> ```ts
> export default defineConfig({
>   plugins: [vue, vueI18n({
>     include: resolve(dirname(fileURLToPath(import.meta.url)), './locales/**'),
>   })],
>   ssr: {
>     // SSG Vue-i18n workaround
>     noExternal: [/vue-i18n/],
>   }
> })
> ```
> 
> I think this should work for other packages too.

yeah, by this way, the "vue-i18n" going work, but I have faced the same issue with "lodash", although I have config it
