### ISSUE TITLE
Vite-SSG failed to build with vue3-easy-data-table

### ISSUE THREAD

**Issue by mrhammadasif** [antfu/vite-ssg#292]
### Describe the bug

Unable to proceed with `vite-ssg build` when using this Library https://github.com/HC200ok/vue3-easy-data-table, Library provides es-module

Getting following error

```
An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/home/projects/github-9mnuxu/node_modules/vue3-easy-data-table/dist/vue3-easy-data-table.es.js:20
import { defineComponent, useCssVars, unref, computed, inject, openBlock, createElementBlock, withModifiers, createElementVNode, normalizeClass, pushScopeId, popScopeId, ref, watch, onMounted, onBeforeUnmount, toDisplayString, Fragment, renderList, useSlots, renderSlot, createCommentVNode, toRefs, provide, normalizeStyle, createBlock, normalizeProps, mergeProps, guardReactiveProps, createTextVNode, createVNode, isRef, createSlots, withCtx } from "vue";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (https://github-9mnuxu.w.staticblitz.com/blitz.b2ae50562a0bdf31ecd871b5c7a8c6dd539613de.js:6:341448)
    at wrapSafe (https://github-9mnuxu.w.staticblitz.com/blitz.b2ae50562a0bdf31ecd871b5c7a8c6dd539613de.js:6:218347)
    at Module._compile (https://github-9mnuxu.w.staticblitz.com/blitz.b2ae50562a0bdf31ecd871b5c7a8c6dd539613de.js:6:218715)
    at Module._extensions..js (https://github-9mnuxu.w.staticblitz.com/blitz.b2ae50562a0bdf31ecd871b5c7a8c6dd539613de.js:6:219743)
    at Module.load (https://github-9mnuxu.w.staticblitz.com/blitz.b2ae50562a0bdf31ecd871b5c7a8c6dd539613de.js:6:217769)
```

Instead when I run `vite build` (non-ssg) it works fine

### Reproduction

https://stackblitz.com/edit/github-9mnuxu?file=src/pages/table.vue&view=editor

### System Info

```Shell
My Personal Macbook Pro (MacOS 12.6):


Stackblitz:
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@mrhammadasif I've it working, patched package.json with (`vue3-easy-data-table`):
```
  "type": "module",
  "exports": {
    ".": {
      "types": "./types/main.d.ts",
      "import": "./dist/vue3-easy-data-table.es.js",
      "require": "./dist/vue3-easy-data-table.umd.js"
    },
    "./dist/style.css": "./dist/style.css"
  },
  "files": [
    "dist",
    "types"
  ],
```

![imagen](https://user-images.githubusercontent.com/6311119/193328442-99b5d00d-70fe-4f08-a022-72b5e859cb8d.png)

**Comment by mrhammadasif** [comment]
So, it's the issue with the `vue3-easy-data-table` library.

I will do the needed
