### ISSUE TITLE
Naive UI Component Error Message

### ISSUE THREAD

**Issue by sariphidayat** [antfu/vite-ssg#304]
### Describe the bug

Hi, everyone. The following error message showed up when I run build:

`[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///***/.vite-ssg-temp/main.mjs:6
import naive, { useMessage, darkTheme, lightTheme } from "naive-ui";
                            ^^^^^^^^^
SyntaxError: Named export 'darkTheme' not found. The requested module 'naive-ui' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'naive-ui';
const { useMessage, darkTheme, lightTheme } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async build (file:///***/node_modules/.pnpm/vite-ssg@0.20.2_l3dnd5kyhx73po3ek4fm3fn5cu/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///***/node_modules/.pnpm/vite-ssg@0.20.2_l3dnd5kyhx73po3ek4fm3fn5cu/node_modules/vite-ssg/dist/node/cli.mjs:20:3)

Node.js v18.9.0`

The compiled code is working though. I'm using [naive-ui](https://www.naiveui.com/) for component library. I added a file with the codes below in modules folder so I can access the naive-ui components on the fly:

`import { type UserModule } from '~/types'
import naive from 'naive-ui'

export const install: UserModule = ({ app, isClient }) => {
    if (isClient) {
        app.use(naive)
    }
}`

Any help would be appreciated.

### Reproduction

pnpm run build

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 29.14 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 85.0.2
    Safari: 16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by censujiang** [comment]
I have same question
