### ISSUE TITLE
@iconify-icons cause "Unexpected token 'export'" error

### ISSUE THREAD

**Issue by rainmanhhh** [antfu/vite-ssg#31]
import @iconify-icons
```
import IconCampsite from '@iconify-icons/carbon/campsite'
```
cause this error
```
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (E:\workspace\vue3\vitesse\.vite-ssg-temp\main.js:26:20)
```
it seems the reason is iconify-icons do not have commonjs dist

so how to deal with modules with only ejs support?

**Comment by hannoeru** [comment]
Try this one: https://github.com/antfu/vite-plugin-icons

**Comment by rainmanhhh** [comment]
need add a type definition to avoid IDE compile error reporting...
```
TS2307: Cannot find module '/@vite-icons/carbon/campsite' or its corresponding type declarations.
```

**Comment by antfu** [comment]
Type declarations fixed in vite-plugin-icons@0.3.3.

**Comment by rainmanhhh** [comment]
> vite-plugin-icons

TS2604: JSX element type 'IconCampsite' does not have any construct or call signatures.

**Comment by rainmanhhh** [comment]
suggest change it to:
```
declare module '/@vite-icons/*' {
  import { FunctionalComponent } from 'vue'
  const component: FunctionalComponent<{style: Partial<CSSStyleDeclaration>}>
  export default component
}
```

**Comment by antfu** [comment]
@rainmanhhh sounds reasonable, would you like to make a quick PR there? Thanks

**Comment by DouglasKyrius** [comment]
The easiest solution would be to install the `@iconify/icons-cryptocurrency` package
