### ISSUE TITLE
NaiveUI Build Error

### ISSUE THREAD

**Issue by censujiang** [antfu/vite-ssg#324]
### Describe the bug

When building SSG, all components of navie-ui cannot be imported

### Reproduction

https://stackblitz.com/edit/github-2sappy

### System Info

```Shell
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///D:/git/VikACG/vue-vikacg-main/.vite-ssg-temp/main.mjs:14
import { useMessage, NModal, NCard, NMessageProvider } from "naive-ui";
                             ^^^^^
SyntaxError: Named export 'NCard' not found. The requested module 'naive-ui' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'naive-ui';
const { useMessage, NModal, NCard, NMessageProvider } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async build (file:///D:/git/VikACG/vue-vikacg-main/node_modules/vite-ssg/dist/shared/vite-ssg.62550b28.mjs:996:87)
    at async Object.handler (file:///D:/git/VikACG/vue-vikacg-main/node_modules/vite-ssg/dist/node/cli.mjs:29:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sadeghbarati** [comment]
I'm facing **Aw, Snap!** error create a GitHub repo instead


I think it's related to SSR problems on undefined `Window` or `Document` even if I import from `naive-ui/es` still has the same error (for sure :zany_face:)

Check this line of vite-ssg, with this you can use dynamic import on any condition
https://github.com/antfu/vite-ssg/blob/16fd2f4275d84584829ee858ccdd94e2122f5d60/src/client/index.ts#L76



- Remove naive-ui component resolver **(NaiveUiResolver)** from `vite.config.ts` 

- Add isClient condition inside `main.ts` or create module inside `src/modules/naive-ui.ts`
```ts
export const createApp = ViteSSG(
  App,
  { routes, base: import.meta.env.BASE_URL },
  async (ctx) => {
    Object.values(import.meta.glob<{ install: UserModule }>('./modules/*.ts', { eager: true }))
          .forEach(i => i.install?.(ctx))
    
    
    // recommended
    if (ctx.isClient) {
      await import('naive-ui').then(({ create, NButton }) => {
        const naive = create({
          components: [NButton],
        })
        ctx.app.use(naive)
      })
    }
    
    // full naive-ui
    if (ctx.isClient) {
      await import('naive-ui').then((naive) => {
        ctx.app.use(naive.default)
      })
    }
}
```

**Comment by censujiang** [comment]
> I'm facing **Aw, Snap!** error create a GitHub repo instead
> 
> I think it's related to SSR problems on undefined `Window` or `Document` even if I import from `naive-ui/es` still has the same error (for sure 🤪)
> 
> Check this line of vite-ssg, with this you can use dynamic import on any condition
> 
> https://github.com/antfu/vite-ssg/blob/16fd2f4275d84584829ee858ccdd94e2122f5d60/src/client/index.ts#L76
> 
> * Remove naive-ui component resolver **(NaiveUiResolver)** from `vite.config.ts`
> * Add isClient condition inside `main.ts` or create module inside `src/modules/naive-ui.ts`
> 
> ```ts
> export const createApp = ViteSSG(
>   App,
>   { routes, base: import.meta.env.BASE_URL },
>   async (ctx) => {
>     Object.values(import.meta.glob<{ install: UserModule }>('./modules/*.ts', { eager: true }))
>           .forEach(i => i.install?.(ctx))
>     
>     
>     // recommended
>     if (ctx.isClient) {
>       await import('naive-ui').then(({ create, NButton }) => {
>         const naive = create({
>           components: [NButton],
>         })
>         ctx.app.use(naive)
>       })
>     }
>     
>     // full naive-ui
>     if (ctx.isClient) {
>       await import('naive-ui').then((naive) => {
>         ctx.app.use(naive.default)
>       })
>     }
> }
> ```

I will try it,thank you!

**Comment by sadeghbarati** [comment]
For component type simply use

```json
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": ["naive-ui/volar"]
  }
}
```

I'm not sure about `naive-ui` compostables use direct import instead

**Comment by 810505339** [comment]
> > I'm facing **Aw, Snap!** error create a GitHub repo instead
> > I think it's related to SSR problems on undefined `Window` or `Document` even if I import from `naive-ui/es` still has the same error (for sure 🤪)
> > Check this line of vite-ssg, with this you can use dynamic import on any condition
> > https://github.com/antfu/vite-ssg/blob/16fd2f4275d84584829ee858ccdd94e2122f5d60/src/client/index.ts#L76
> > 
> > 
> > * Remove naive-ui component resolver **(NaiveUiResolver)** from `vite.config.ts`
> > * Add isClient condition inside `main.ts` or create module inside `src/modules/naive-ui.ts`
> > 
> > ```ts
> > export const createApp = ViteSSG(
> >   App,
> >   { routes, base: import.meta.env.BASE_URL },
> >   async (ctx) => {
> >     Object.values(import.meta.glob<{ install: UserModule }>('./modules/*.ts', { eager: true }))
> >           .forEach(i => i.install?.(ctx))
> >     
> >     
> >     // recommended
> >     if (ctx.isClient) {
> >       await import('naive-ui').then(({ create, NButton }) => {
> >         const naive = create({
> >           components: [NButton],
> >         })
> >         ctx.app.use(naive)
> >       })
> >     }
> >     
> >     // full naive-ui
> >     if (ctx.isClient) {
> >       await import('naive-ui').then((naive) => {
> >         ctx.app.use(naive.default)
> >       })
> >     }
> > }
> > ```
> 
> I will try it,thank you!

```
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:4852) UnhandledPromiseRejectionWarning: file:///D:/project/vue-naive-template/.vite-ssg-temp/main.mjs:13
import { darkTheme, zhCN as zhCN$1, dateZhCN } from "naive-ui";
                    ^^^^
SyntaxError: Named export 'zhCN' not found. The requested module 'naive-ui' is a CommonJS module, which may not support all
 module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'naive-ui';
const { darkTheme, zhCN: zhCN$1, dateZhCN } = pkg;
```

i try it , zhCN not found ~😟😟😟

**Comment by joeyhuang0235** [comment]
Workaround: 

```js
// vite.config.ts

export default defineConfig({
  // ...,

  ssr: {
    noExternal: ['naive-ui'],
  },
})
```

**Comment by jupeng-code** [comment]
> 解决方法：
> 
> ```js
> // vite.config.ts
> 
> export default defineConfig({
>   // ...,
> 
>   ssr: {
>     noExternal: ['naive-ui'],
>   },
> })
> ```

This method is feasible

**Comment by jupeng-code** [comment]
> 解决方法：
> 
> ```js
> // vite.config.ts
> 
> export default defineConfig({
>   // ...,
> 
>   ssr: {
>     noExternal: ['naive-ui'],
>   },
> })
> ```


This method is feasible
