### ISSUE TITLE
Build hanging after completing build

### ISSUE THREAD

**Issue by waelio** [antfu/vite-ssg#60]
Hello
My build succeeds but does not exit. Kinda hangin.

```bash
# Environment
$ pnpm -v
6.7.6
$ node  -v
v16.0.0

Windows 10
```
**To reproduce:**
` pnpm build`

**Expected**
Exiting build process after completion, but it does not. 

**Result After command locally**
```bash
[vite-ssg] Build for client...
vite v2.3.7 building for production...
✓ 254 modules transformed.
dist/index.html                                1.56kb
dist/manifest.webmanifest                      0.39kb
dist/ssr-manifest.json                         39.03kb
dist/assets/virtual_pwa-register.cfcd7e2b.js   0.57kb / brotli: 0.32kb
dist/assets/[...all].6802bd45.js               0.22kb / brotli: 0.17kb
dist/assets/timeline.fcca43f1.js               1.19kb / brotli: 0.57kb
dist/assets/index.d6f56c2f.js                  3.72kb / brotli: 1.12kb
dist/assets/terms.2181aee9.js                  10.52kb / brotli: 2.80kb
dist/assets/privacy.df4482c2.js                13.82kb / brotli: 2.19kb
dist/assets/index.4de370db.js                  5.14kb / brotli: 1.45kb
dist/assets/contact.c51e592b.js                4.54kb / brotli: 1.56kb
dist/assets/about.8f0e4987.js                  0.66kb / brotli: 0.28kb
dist/assets/home.4d426a09.js                   0.50kb / brotli: 0.30kb
dist/assets/404.dca62e88.js                    1.01kb / brotli: 0.51kb
dist/assets/index.b25c940d.css                 0.22kb / brotli: 0.10kb
dist/assets/contact.202d630b.css               1.02kb / brotli: 0.30kb
dist/assets/app.777cd524.js                    24.81kb / brotli: 7.26kb
dist/assets/app.d5ba3325.css                   19.00kb / brotli: 3.98kb
dist/assets/vendor.a8def4eb.js                 277.22kb / brotli: 81.81kb

[vite-ssg] Build for server...
vite v2.3.7 building SSR bundle for production...
✓ 66 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.39kb
.vite-ssg-temp/main.js                     152.01kb
.vite-ssg-temp/assets/style.02cce71f.css   24.45kb

[vite-ssg] Rendering Pages... (6)
dist/index.html 8.45kb
dist/terms.html 18.67kb
dist/contact.html       11.64kb
dist/privacy.html       21.80kb
dist/about.html 10.02kb
dist/timeline.html      15.50kb

[vite-ssg] Build finished.
# It never exists.!
```
Same output on netlify, I can paste it here is needed.

This my package.json
```js
// package.json
"dependencies": {
    "@feathersjs/adapter-commons": "^4.5.11",
    "@feathersjs/authentication-client": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/socketio-client": "^4.5.11",
    "@vitejs/plugin-vue-jsx": "^1.1.5",
    "@vueuse/core": "^4.11.2",
    "@vueuse/head": "^0.5.1",
    "feathers-hooks-common": "^5.0.6",
    "feathers-pinia": "^0.12.9",
    "fs.promises": "^0.1.2",
    "js-cookie": "^2.2.1",
    "moment": "^2.29.1",
    "nprogress": "^0.2.0",
    "path": "^0.12.7",
    "pinia": "^2.0.0-beta.2",
    "prism-theme-vars": "^0.2.2",
    "socket.io-client": "^2.0.0",
    "vue": "^3.0.11",
    "vue-i18n": "^9.1.6",
    "vue-property-decorator": "^9.1.2",
    "vue-router": "^4.0.8"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.6.5",
    "@iconify/json": "^1.1.353",
    "@intlify/vite-plugin-vue-i18n": "^2.2.0",
    "@types/nprogress": "^0.2.0",
    "@typescript-eslint/eslint-plugin": "^4.26.0",
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.11",
    "@vue/server-renderer": "^3.0.11",
    "@windicss/plugin-animations": "^1.0.9",
    "cross-env": "^7.0.3",
    "eslint": "^7.28.0",
    "https-localhost": "^4.6.5",
    "markdown-it-prism": "^2.1.6",
    "pnpm": "^6.7.1",
    "scss": "^0.2.4",
    "typescript": "^4.3.2",
    "vite": "^2.3.7",
    "vite-plugin-components": "^0.10.4",
    "vite-plugin-icons": "^0.6.1",
    "vite-plugin-md": "^0.6.7",
    "vite-plugin-pages": "^0.12.2",
    "vite-plugin-pwa": "^0.7.3",
    "vite-plugin-vue-layouts": "^0.3.1",
    "vite-plugin-windicss": "^0.16.7",
    "vite-ssg": "^0.11.2",
    "vue-tsc": "^0.1.7"
  }
```

Thanks you

**Comment by userquin** [comment]
try to update to latest version `0.11.4`, you have `0.11.2'.

beware, on latest version, we updated to latest versions of `vite` and `vue` (also `vue-router` and `useHead`), see `package.json`

**Comment by waelio** [comment]
this is the outcome of the update ... complete meltdown 🤦‍♂️

```bash
re-bundling dependencies:   
  @feathersjs/feathers       
  @feathersjs/socketio-client
  vite-ssg
  socket.io-client
  pinia
  (...and 8 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/.pnpm/vite-ssg@0.11.4_acebffa845943e7fac8d1e0027afd195/node_modules/vite-ssg/dist/chunk-6HTX7RH6.mjs:31:8: error: No matching 
export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "defineComponent"
    31 │ import {defineComponent} from "vue";
       ╵         ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:23:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "defineComponent"
    23 │   defineComponent,
       ╵   ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:24:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "inject"
    24 │   inject,
       ╵   ~~~~~~

 > node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:25:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "onBeforeUnmount"
    25 │   onBeforeUnmount,
       ╵   ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:26:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "ref"
    26 │   ref,
       ╵   ~~~

 > node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:27:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "watchEffect"
    27 │   watchEffect
       ╵   ~~~~~~~~~~~

 > node_modules/.pnpm/vite-ssg@0.11.4_acebffa845943e7fac8d1e0027afd195/node_modules/vite-ssg/dist/index.mjs:12:8: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "createSSRApp"
    12 │ import {createSSRApp, createApp as createClientApp} from "vue";
       ╵         ~~~~~~~~~~~~

 > node_modules/.pnpm/vite-ssg@0.11.4_acebffa845943e7fac8d1e0027afd195/node_modules/vite-ssg/dist/index.mjs:12:22: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "createApp"
    12 │ import {createSSRApp, createApp as createClientApp} from "vue";
       ╵                       ~~~~~~~~~

 > node_modules/.pnpm/vite-ssg@0.11.4_acebffa845943e7fac8d1e0027afd195/node_modules/vite-ssg/dist/index.mjs:13:8: error: No matching export in "node_modules/.pnpm/vue-router@3.5.1/node_modules/vue-router/dist/vue-router.esm.js" for import "createMemoryHistory"
    13 │ import {createMemoryHistory, createRouter, createWebHistory} from "vue-router";
       ╵         ~~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/vite-ssg@0.11.4_acebffa845943e7fac8d1e0027afd195/node_modules/vite-ssg/dist/index.mjs:13:29: error: No matching export in "node_modules/.pnpm/vue-router@3.5.1/node_modules/vue-router/dist/vue-router.esm.js" for import "createRouter"
    13 │ import {createMemoryHistory, createRouter, createWebHistory} from "vue-router";
       ╵                              ~~~~~~~~~~~~

 > node_modules/.pnpm/vite-ssg@0.11.4_acebffa845943e7fac8d1e0027afd195/node_modules/vite-ssg/dist/index.mjs:13:43: error: No matching export in "node_modules/.pnpm/vue-router@3.5.1/node_modules/vue-router/dist/vue-router.esm.js" for import "createWebHistory"
    13 │ import {createMemoryHistory, createRouter, createWebHistory} from "vue-router";
       ╵                                            ~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 11 errors:
node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:23:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "defineComponent"
node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:24:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "inject"
node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:25:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "onBeforeUnmount"
node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:26:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "ref"
node_modules/.pnpm/@vueuse+head@0.6.0_vue@2.6.14/node_modules/@vueuse/head/dist/index.mjs:27:2: error: No matching export in "node_modules/.pnpm/vue@2.6.14/node_modules/vue/dist/vue.runtime.esm.js" for import "watchEffect"
...
    at failureErrorWithLog (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1449:15)
    at C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1129:7)
    at C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1236:14
    at C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
 ERROR  Command failed with exit code 1.
```
I'm dead

**Comment by userquin** [comment]
just check our `package.json`, I had the same problem  yesterday ;)...

Can you show me your `package.json`?

**Comment by userquin** [comment]
upps, `vue2`, maybe you need to up also the `vite-plugin-vue2`...

**Comment by userquin** [comment]
I'm testing rigth now for an issue on `vite-plugin-pwa`... Are you using `vue-demi`?

**Comment by waelio** [comment]
```bash
"dependencies": {
    "@feathersjs/adapter-commons": "^4.5.11",
    "@feathersjs/authentication-client": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/socketio-client": "^4.5.11",
    "@vitejs/plugin-vue-jsx": "^1.1.5",
    "@vueuse/core": "^5.0.3",
    "@vueuse/head": "^0.6.0",
    "feathers-hooks-common": "^5.0.6",
    "feathers-pinia": "^0.12.9",
    "fs.promises": "^0.1.2",
    "js-cookie": "^2.2.1",
    "moment": "^2.29.1",
    "nprogress": "^0.2.0",
    "path": "^0.12.7",
    "pinia": "^0.5.2",
    "prism-theme-vars": "^0.2.2",
    "socket.io-client": "^4.1.2",
    "vue": "^2.6.14",
    "vue-i18n": "^8.24.4",
    "vue-property-decorator": "^9.1.2",
    "vue-router": "^3.5.1"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.6.6",
    "@iconify/json": "^1.1.358",
    "@intlify/vite-plugin-vue-i18n": "^2.2.1",
    "@types/nprogress": "^0.2.0",
    "@typescript-eslint/eslint-plugin": "^4.27.0",
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.1.1",
    "@vue/composition-api": "^1.0.0-rc.12",
    "@vue/server-renderer": "^3.1.1",
    "@windicss/plugin-animations": "^1.0.9",
    "cross-env": "^7.0.3",
    "eslint": "^7.28.0",
    "https-localhost": "^4.6.5",
    "markdown-it-prism": "^2.1.6",
    "pnpm": "^6.7.6",
    "scss": "^0.2.4",
    "typescript": "^4.3.4",
    "vite": "^2.3.7",
    "vite-plugin-components": "^0.11.2",
    "vite-plugin-icons": "^0.6.2",
    "vite-plugin-md": "^0.6.7",
    "vite-plugin-pages": "^0.13.1",
    "vite-plugin-pwa": "^0.8.1",
    "vite-plugin-vue-layouts": "^0.3.1",
    "vite-plugin-windicss": "^1.0.4",
    "vite-ssg": "^0.11.4",
    "vue-tsc": "^0.1.7"
  }
```

**Comment by userquin** [comment]
just compare with `vite-ssg` versions: I think `pinia` also needs to be upgraded.

See `package.json` history...

`0.11.3` => was wrong
https://github.com/antfu/vite-ssg/commit/c00123714ccc931c5cb7258afcf367a1271c0281#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

and `0.11.4` => updated `typescrupt` + `pinia`

https://github.com/antfu/vite-ssg/commit/bb58f7d2da060ad03065ee7e8317f90a8b9675b3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by waelio** [comment]
I've been running the same command, `pnpm update --latest`
I;ll deepdive in package.json

**Comment by waelio** [comment]
Okay, so far this what I got, it still broken but seems less errors.
Here is the console log:
```bash
$ pnpm dev

> waelio.com@0.1.15 dev C:\Users\wahbe\Documents\GitHub\waelio.com
> vite --port 3333 --open

Pre-bundling dependencies:
  @feathersjs/feathers
  @feathersjs/socketio-client
  socket.io-client
  vite-ssg
  pinia
  (...and 8 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/.pnpm/@vue+composition-api@1.0.0-beta.1_vue@3.1.1/node_modules/@vue/composition-api/dist/vue-composition-api.esm.js:1:7: error: No matching export in "node_modules/.pnpm/vue@3.1.1/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    1 │ import Vue from 'vue';
      ╵        ~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/.pnpm/@vue+composition-api@1.0.0-beta.1_vue@3.1.1/node_modules/@vue/composition-api/dist/vue-composition-api.esm.js:1:7: error: No matching export in "node_modules/.pnpm/vue@3.1.1/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    at failureErrorWithLog (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1449:15)    
    at C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:921:63)       
    at buildResponseToResult (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1129:7)   
    at C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:1236:14
    at C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:706:9)     
    at Socket.readFromStdout (C:\Users\wahbe\Documents\GitHub\waelio.com\node_modules\.pnpm\esbuild@0.12.9\node_modules\esbuild\lib\main.js:576:7)    
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
 ERROR  Command failed with exit code 1.
```
Here is the new package dependencies 
```js
  "scripts": {
    "dev": "vite --port 3333 --open",
    "build": "cross-env NODE_ENV=production vite-ssg build",
    "preview": "vite preview",
    "preview-https": "serve dist"
  },
  "dependencies": {
    "@feathersjs/adapter-commons": "^4.5.11",
    "@feathersjs/authentication-client": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/socketio-client": "^4.5.11",
    "@vitejs/plugin-vue-jsx": "^1.1.5",
    "@vueuse/core": "^5.0.3",
    "@vueuse/head": "^0.6.0",
    "feathers-hooks-common": "^5.0.6",
    "feathers-pinia": "^0.12.9",
    "fs.promises": "^0.1.2",
    "js-cookie": "^2.2.1",
    "moment": "^2.29.1",
    "nprogress": "^0.2.0",
    "path": "^0.12.7",
    "pinia": "0.5.2",
    "prism-theme-vars": "^0.2.2",
    "socket.io-client": "^4.1.2",
    "vue-i18n": "^8.24.4",
    "vue-property-decorator": "^9.1.2"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.6.6",
    "@iconify/json": "^1.1.358",
    "@intlify/vite-plugin-vue-i18n": "^2.2.1",
    "@types/nprogress": "^0.2.0",
    "@typescript-eslint/eslint-plugin": "^4.27.0",
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.1.1",
    "@vue/composition-api": "^1.0.0-beta.1",
    "@vue/server-renderer": "^3.1.1",
    "@windicss/plugin-animations": "^1.0.9",
    "cross-env": "^7.0.3",
    "eslint": "^7.28.0",
    "https-localhost": "^4.6.5",
    "markdown-it-prism": "^2.1.6",
    "pnpm": "^6.7.6",
    "scss": "^0.2.4",
    "typescript": "^4.3.4",
    "vite": "^2.3.7",
    "vite-plugin-components": "^0.11.2",
    "vite-plugin-icons": "^0.6.2",
    "vite-plugin-md": "^0.6.7",
    "vite-plugin-pages": "^0.13.1",
    "vite-plugin-pwa": "^0.8.1",
    "vite-plugin-vue-layouts": "^0.3.1",
    "vite-plugin-windicss": "^1.0.4",
    "vite-ssg": "^0.11.4",
    "vue": "3.1.1",
    "vue-demi": "^0.9.1",
    "vue-router": "^4.0.9",
    "vue-tsc": "^0.1.7"
  },
  "peerDependencies": {
    "@vue/composition-api": "^1.0.0-beta.1",
    "vue": "2.6.14"
  }
```

**Comment by antfu** [comment]
Please make sure you are using them same target Vue version for your dependencies first. (also note vite-ssg does not support Vue 2)

**Comment by waelio** [comment]
> I'm testing rigth now for an issue on `vite-plugin-pwa`... Are you using `vue-demi`?

I never installed vue-demi, it came as part of vitesse.

**Comment by waelio** [comment]
> Please make sure you are using them same target Vue version for your dependencies first. (also note vite-ssg does not support Vue 2)

looking at my package.json do you see conflicting versions?
I don't need vue2 in anything I am doing, nevertheless, it seems that pinia and feathers-pinia are refencing vue@2.6.14 that's why added them as peer dependencies

**Comment by antfu** [comment]
https://github.com/posva/pinia#pinia you will need v2.0 for Vue 3 support.

GitHub Issues are for bug report and tracking. Please use Discord or StackOverflow to ask questions.

**Comment by waelio** [comment]
Here is the outcome of a build command:
`[vite-plugin-pwa] 'default' is not exported by node_modules\.pnpm\vue@3.1.1\node_modules\vue\dist\vue.runtime.esm-bundler.js, imported by node_modules\.pnpm\@vue+composition-api@1.0.0-rc.12_vue@3.1.1\node_modules\@vue\composition-api\dist\vue-composition-api.esm.js
file: C:/Users/wahbe/Documents/GitHub/waelio.com/node_modules/.pnpm/@vue+composition-api@1.0.0-rc.12_vue@3.1.1/node_modules/@vue/composition-api/dist/vue-composition-api.esm.js:1:7
1: import Vue from 'vue';
          ^
2: 
3: var toString = function (x) { return Object.prototype.toString.call(x); };`

**Comment by userquin** [comment]
If you are using the  `vue` virtual module of pwa plugin, just try to add the mixin described on the issue open on the pwa repo, the problem should be gone.

**Comment by waelio** [comment]
> @waelio If you are using the  `vue` virtual module of pwa plugin, just try to add the mixin described on the issue open on the pwa repo, the problem should be gone.
> 
> 
> 
> https://github.com/antfu/vite-plugin-pwa/issues/81#issuecomment-864327612

My problem was calling feathers which uses sockets. 
After discussion with the feathers team they told me I can't use sockets in my service worker's. 
I am creating a new 'useSubscriptions.ts' uses events. 
I'll post the solution once it's ready and tested. In the meanwhile it's not a bad idea to somehow let other know. 
Thanks
