### ISSUE TITLE
SSG Builds broken - Need quick help configuring builds

### ISSUE THREAD

**Issue by armenr** [antfu/vite-ssg#83]
I recently added some new packages/code to my vite-ssg project (using vitesse). All build modes were working without issue until the addition of this new code + npm packages. I had working vite builds + working SSG builds.

Now, I am able to build with `cross-env NODE_ENV=production vite build` but cannot build with `cross-env NODE_ENV=production vite-ssg build`

I'm going to guess that there are some changes I need to make to my vite config and/or to SSG, but I'm stuck. Any help would be much appreciated! :) 

### Error trace
```
[vite-ssg] Build for server...
vite v2.4.4 building SSR bundle for production...
✓ 573 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.37kb
.vite-ssg-temp/assets/style.c59dba99.css   244.38kb
.vite-ssg-temp/main.js                     634.65kb
/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/@aws-amplify+ui-components@1.7.1_aws-amplify@4.2.2/node_modules/@aws-amplify/ui-components/dist/components/index.js:1
(function (exports, require, module, __filename, __dirname) { import { attachShadow, h, Host, createEvent, proxyCustomElement } from '@stencil/core/internal/client';
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at p._moduleCompile (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:2705)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at n (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:2472)
    at Module.<anonymous> (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/.vite-ssg-temp/main.js:22:13)
    at Module.o._compile (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:2778)
/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client:
 ERROR  @testProjtestProj/client@0.0.1 build:ssg: `cross-env NODE_ENV=production vite-ssg build`
Exit status 1
 ERROR  Command failed with exit code 1.
```

### Full build logs
```
╰─ pnpm build:client:pnpm:ssg

> testProjtestProj@0.0.1 build:client:pnpm:ssg /Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2
> pnpm run build:ssg --filter @testProjtestProj/client


> @testProjtestProj/client@0.0.1 build:ssg /Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client
> cross-env NODE_ENV=production vite-ssg build


[vite-ssg] Build for client...
vite v2.4.4 building for production...
✓ 2185 modules transformed.
dist/assets/color.473bc8ca.png                 10.11kb
dist/assets/primeicons.7362b83d.eot            56.21kb
dist/assets/primeicons.c1e93246.ttf            56.04kb
dist/assets/primeicons.3929b551.woff           56.11kb
dist/assets/primeicons.8f9d2aaf.svg            229.14kb
dist/index.html                                1.36kb
dist/manifest.webmanifest                      0.37kb
dist/ssr-manifest.json                         346.73kb
dist/assets/virtual_pwa-register.ecd604b6.js   5.44kb / brotli: 1.98kb
dist/assets/signin.5f646ef8.js                 5.79kb / brotli: 1.84kb
dist/assets/x.7978b5aa.js                      0.47kb / brotli: 0.29kb
dist/assets/landingtwo.d40769b6.js             7.74kb / brotli: 2.37kb
dist/assets/dicom-overlay.af56634f.js          0.63kb / brotli: 0.33kb
dist/assets/home.e25fc82f.js                   9.81kb / brotli: 3.57kb
dist/assets/mail.3f6051bf.js                   0.55kb / brotli: 0.33kb
dist/assets/calendar.c651f22a.js               0.77kb / brotli: 0.41kb
dist/assets/about.ccc1ce3a.js                  1.79kb / brotli: 0.60kb
dist/assets/README.c331fb6e.js                 1.22kb / brotli: 0.43kb
dist/assets/[name].800cb756.js                 1.34kb / brotli: 0.72kb
dist/assets/landingone.6e27b29d.js             19.23kb / brotli: 4.38kb
dist/assets/[...all].4d5e4be5.js               0.22kb / brotli: 0.16kb
dist/assets/directory.e153bbc9.js              20.11kb / brotli: 4.23kb
dist/assets/404.c02b86e9.js                    1.70kb / brotli: 0.74kb
dist/assets/[name].0c88a31b.js                 8.26kb / brotli: 2.56kb
dist/assets/home.50d47f73.js                   12.31kb / brotli: 2.86kb
dist/assets/dom.29d9f284.js                    18.14kb / brotli: 4.84kb
dist/assets/signin.12fef205.css                0.36kb / brotli: 0.17kb
dist/assets/app.c6727523.js                    49.99kb / brotli: 10.95kb
dist/assets/core-js.892b7ba3.js                77.26kb / brotli: 22.19kb
dist/assets/app.bd2aea20.css                   208.54kb / brotli: 23.86kb
dist/assets/vendor.cb864961.js                 924.80kb / brotli: skipped (large chunk)

(!) Some chunks are larger than 500kb after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

[vite-ssg] Build for server...
vite v2.4.4 building SSR bundle for production...
✓ 573 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.37kb
.vite-ssg-temp/assets/style.c59dba99.css   244.38kb
.vite-ssg-temp/main.js                     634.65kb
/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/@aws-amplify+ui-components@1.7.1_aws-amplify@4.2.2/node_modules/@aws-amplify/ui-components/dist/components/index.js:1
(function (exports, require, module, __filename, __dirname) { import { attachShadow, h, Host, createEvent, proxyCustomElement } from '@stencil/core/internal/client';
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at p._moduleCompile (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:2705)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at n (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:2472)
    at Module.<anonymous> (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/.vite-ssg-temp/main.js:22:13)
    at Module.o._compile (/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client/node_modules/.pnpm/jiti@1.11.0/node_modules/jiti/dist/v8cache.js:2:2778)
/Users/armenr/Development/testProj-testProj-workspace/testProj-vitesse-test-2/packages/client:
 ERROR  @testProjtestProj/client@0.0.1 build:ssg: `cross-env NODE_ENV=production vite-ssg build`
Exit status 1
 ERROR  Command failed with exit code 1.
```

**Comment by antfu** [comment]
Can you share the reproduction?

**Comment by armenr** [comment]
@antfu - https://github.com/armenr/amplify-vitesse-repro

`pnpm i`
`pnpm build`

Modified files:

- vite config
- components/Authwrapper
- package.json (rollup plugin, zen-observable, amplify libs, package resolution override)

**Comment by armenr** [comment]
@antfu - just a gentle ping...Still haven't been able to work this out, but if it's not the SSG library's issue, I'm happy to close this as being outside of this repo's/library's scope.

**Comment by userquin** [comment]
@armenr I clone the repo a few days ago, and I cannot just build it: I have a 9900K with 64GB of ram and a SSD 970 PRO and just running the build command I must cancel it while compiling the 817 module, never stops after 10min waiting...

**Comment by armenr** [comment]
@userquin it builds with vite build no problem.

I think there might be something with your environment...

It builds on my Intel 16" MacBook Pro, as well as on an m1 pro, as well as in a docker container on AWS Codebuild, in Windows on an AMD, and also circleCI.

**Comment by userquin** [comment]
@armenr Build with this `script` 😅:
```json
    "build:vite": "cross-env NODE_ENV=production vite build --debug",
```
The build stops here, seems something blocking while processing `css` but other builds stop in another modules:
```shell
vite v2.4.4 building for production...
transforming (779) node_modules\.pnpm\fast-xml-parser@3.19.0\node_modules\fast-xml-parser\src\validator.js  vite:resolve 0ms   ./markdown.css -> F:/work/projects/quini/GitHub/amplify-vitesse-repro/src/styles/mar
kdown.css +0ms
  vite:resolve 2ms   prism-theme-vars/base.css -> F:/work/projects/quini/GitHub/amplify-vitesse-repro/node_modules/.pnpm/prism-theme-vars@0.2.2/node_modules/prism-theme-vars/base.css +14ms
transforming (820) src\styles\main.css
```
![imagen](https://user-images.githubusercontent.com/6311119/128863067-059fa60c-4d69-4f4a-a9a6-6a5d0ca68581.png)

**Comment by userquin** [comment]
@armenr I found this https://discord.com/channels/804011606160703521/804440184875122730/872708020612759593 maybe related?

**Comment by flavionn** [comment]
hey guys thanks for everything

I'm in the same situation.

I cloned vitesse and just added @vueuse/firebase and firebase.

So when I run pnpm build it is freezing in `[vite-ssg] Build finished.`

I noticed that when I delete the project's firebase, the build works correctly and doesn't freeze.

```ts
import firebase from 'firebase/app'
import 'firebase/firestore'
import { useFirestore } from '@vueuse/firebase/useFirestore'
```

I tried the build on my computer (linux), Vercel and Netlify.

**Comment by hoanghadu** [comment]
I have problems with vite-ssg and firebase too. I clone vitesse and add a file at ~/composables/products.ts

```js
import firebase from 'firebase/compat/app'
import 'firebase/compat/firestore'
import { useFirestore } from '@vueuse/firebase/useFirestore'
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY as string,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN as string,
  databaseURL: import.meta.env.VITE_FIREBASE_DATABASE_URL as string,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID as string,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET as string,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID as string,
  appId: import.meta.env.VITE_FIREBASE_APP_ID as string,
}
const db = firebase.initializeApp(firebaseConfig).firestore()
const products = useFirestore(db.collection('products'), undefined, { autoDispose: false })
export { db, products }
```
Then I import `products` in a page, it shows correctly. However, whenever I run `pnpm build`, an error occurs.
```
[vite-ssg] Rendering Pages... (4)
[vite-ssg] Critical CSS generation enabled via `critters`
/home/quan/wp/fe-test/.vite-ssg-temp/main.js:3039
    throw a2;
    ^

ReferenceError: Headers is not defined
    at new qd (/home/quan/wp/fe-mhu3/.vite-ssg-temp/main.js:4020:16)
    at pd.g (/home/quan/wp/fe-mhu3/.vite-ssg-temp/main.js:4004:10)
    at X$1.k$1.ea (/home/quan/wp/fe-mhu3/.vite-ssg-temp/main.js:4152:28)
    at kc$1 (/home/quan/wp/fe-mhu3/.vite-ssg-temp/main.js:3354:98)
    at ic$1 (/home/quan/wp/fe-mhu3/.vite-ssg-temp/main.js:3338:3)
    at Id.k$1.Ha (/home/quan/wp/fe-mhu3/.vite-ssg-temp/main.js:4492:95)
    at Db (/home/quan/wp/fe-mhu3/.vite-ssg-temp/main.js:3058:12)
 ELIFECYCLE  Command failed with exit code 1.
```
Please help.

**Comment by NunoSav** [comment]
@armenr did you end up solving the issue?

**Comment by RebeccaStevens** [comment]
I think I'm having this same error, but for me `vite build` works fine but `vite-ssg build` fails.

**Comment by lucas-pouchot** [comment]
Hello, I have the same issue using FullCalendar,
It require to import `@fullcalendar/core/vdom` to work :
https://fullcalendar.io/docs/vue

But this will work with a `vite build` and break with `vite-ssg build`

```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
C:\Users\PC\WebstormProjects\ternat-front\node_modules\.pnpm\@fullcalendar+core@5.11.0\node_modules\@fullcalendar\core\vdom.js:1
import { __extends } from 'tslib';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

My module:

``` ts
import '@fullcalendar/core/vdom';
import FullCalendar from '@fullcalendar/vue3';
import type { UserModule } from '~/types';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const install: UserModule = ({ app, router, isClient }) => {
    app.component('FullCalendar', FullCalendar);
};
```

**Comment by wilfredinni** [comment]
I have the same error, but with vue macos

```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:19380) UnhandledPromiseRejectionWarning: /home/carlos/projects/python-cheatsheet/node_modules/.pnpm/vue@3.2.37/node_modules/vue/macros.d.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Module.<anonymous> (/home/carlos/projects/python-cheatsheet/.vite-ssg-temp/main.cjs:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It works fine with `vite build` command

**Comment by armenr** [comment]
@NunoSav - In my case, I didn't need static builds, and I had no benefit from static builds. For my use-case, Vitesse worked fine with standard SPA/PWA builds, and non static/server-side-generated.

So, unfortunately, no. 

Also, the likely cause of the problem is not actually Vitesse...but rather some component or library/dependency you are using, that isn't SSR/SSG friendly.
