### ISSUE TITLE
Examples aren't work.

### ISSUE THREAD

**Issue by yesworld** [antfu/vite-ssg#99]
1.  Clone project
`git clone git@github.com:antfu/vite-ssg.git`
2. Install modules
`npm install`
3. Run any examples and I get an error:
```bash
$ npm run example:dev

> vite-ssg@0.15.1 example:dev /Users/yesworld/temp/vite-ssg
> npm run copy-readme-files && npm -C examples/multiple-pages run dev


> vite-ssg@0.15.1 copy-readme-files /Users/yesworld/temp/vite-ssg
> esno scripts/copy-readme-files.ts


> @ dev /Users/yesworld/temp/vite-ssg/examples/multiple-pages
> cross-env DEBUG=vite-ssg:* vite

sh: cross-env: command not found
```

4. Ok. I have installed **cross-env**
`npm i -D cross-env`

5. Run `npm run example:dev or npm run example:build or something`
```bash
$ npm run example:build

> vite-ssg@0.15.1 example:build /Users/yesworld/temp/vite-ssg
> npm run copy-readme-files && npm -C examples/multiple-pages run build


> vite-ssg@0.15.1 copy-readme-files /Users/yesworld/temp/vite-ssg
> esno scripts/copy-readme-files.ts


> @ build /Users/yesworld/temp/vite-ssg/examples/multiple-pages
> cross-env DEBUG=vite-ssg:* vite-ssg build

events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: spawn vite-ssg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn vite-ssg',
  path: 'vite-ssg',
  spawnargs: [ 'build' ]
}
```

**Comment by hannoeru** [comment]
You need to build the code first, using `pnpm build`.

**Comment by yesworld** [comment]
Thanks for your reply, @hannoeru. I have executed this command, but the same problem.


```bash
$ npm run build

> vite-ssg@0.15.1 build /Users/yesworld/temp/vite-ssg
> rimraf dist && npm run build:module && npm run copy-single-page-dts


> vite-ssg@0.15.1 build:module /Users/yesworld/temp/vite-ssg
> tsup src/index.ts src/client/single-page.ts src/node/cli.ts --dts --format cjs,esm

 CLI  Building entry: src/index.ts, src/client/single-page.ts, src/node/cli.ts
 CLI  Using tsconfig: /Users/yesworld/temp/vite-ssg/tsconfig.json
 CLI  tsup v4.14.0
 CLI  Target: node12
 CJS  Build start
 ESM  Build start
 ESM  Build success in 32ms
 CJS  Build success in 70ms
 DTS  Build start
 DTS  Build success in 1296ms

> vite-ssg@0.15.1 copy-single-page-dts /Users/yesworld/temp/vite-ssg
> esno scripts/copy-single-page-dts.ts
```

Need to install **cross-env, vite-plugin-md , vite-plugin-pages** and etc... Everything that is in the **package.json** file in the example/* folder.

```bash
$ npm run example:dev

> vite-ssg@0.15.1 example:dev /Users/yesworld/temp/vite-ssg
> npm run copy-readme-files && npm -C examples/multiple-pages run dev


> vite-ssg@0.15.1 copy-readme-files /Users/yesworld/temp/vite-ssg
> esno scripts/copy-readme-files.ts


> @ dev /Users/yesworld/temp/vite-ssg/examples/multiple-pages
> cross-env DEBUG=vite-ssg:* vite

sh: cross-env: command not found


$ npm i -D  cross-env
```

```bash
$npm run example:dev

> vite-ssg@0.15.1 example:dev /Users/yesworld/temp/vite-ssg
> npm run copy-readme-files && npm -C examples/multiple-pages run dev


> vite-ssg@0.15.1 copy-readme-files /Users/yesworld/temp/vite-ssg
> esno scripts/copy-readme-files.ts


> @ dev /Users/yesworld/temp/vite-ssg/examples/multiple-pages
> cross-env DEBUG=vite-ssg:* vite

failed to load config from /Users/yesworld/temp/vite-ssg/examples/multiple-pages/vite.config.ts
error when starting dev server:
Error: Cannot find module 'vite-plugin-md'
Require stack:
- /Users/yesworld/temp/vite-ssg/examples/multiple-pages/vite.config.ts
- /Users/yesworld/temp/vite-ssg/node_modules/vite/dist/node/chunks/dep-1be34a63.js
- /Users/yesworld/temp/vite-ssg/node_modules/vite/dist/node/cli.js
- /Users/yesworld/temp/vite-ssg/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/yesworld/temp/vite-ssg/examples/multiple-pages/vite.config.ts:29:40)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/yesworld/temp/vite-ssg/node_modules/vite/dist/node/chunks/dep-1be34a63.js:77161:20)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
```


I tried to install the modules from the example folder
```bash
$ cd examples/multiple-pages

$ npm i 
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

**Comment by antfu** [comment]
We uses pnpm instead of npm

**Comment by yesworld** [comment]
Ok, I'll be using **pnpm.**  Thanks, guys!
